permalink: pretty
title: Visual Design, Social Media Production, and Web Development
description: Sean August Horvath 2023 portfolio designed in Webflow to showcase hand drawn illustrations and video productions. 
baseurl: ""
url: "https://visual-producer.august.style"
